# Generated by Django 2.0.4 on 2018-05-14 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinces', models.IntegerField(default=7)),
                ('paalikas', models.IntegerField(default=460)),
                ('municipalities', models.IntegerField(default=276)),
                ('total_population', models.IntegerField(default=29624035)),
                ('area', models.CharField(default='147,181 sq.km', max_length=200)),
                ('population_density', models.IntegerField(null=True)),
                ('poverty_rate', models.FloatField(null=True)),
                ('literacy_rate', models.FloatField(null=True)),
                ('population_under_poverty_line', models.IntegerField(null=True)),
                ('per_capita_income', models.IntegerField(null=True)),
                ('human_development_index', models.FloatField(null=True)),
                ('gdp', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictSpending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_spend', models.FloatField()),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_spending', to='core.District')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=200)),
                ('years', models.IntegerField()),
                ('source', models.CharField(max_length=250)),
                ('indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_data_province_indicator', to='core.Indicator')),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LayerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=250)),
                ('notes', models.TextField()),
                ('file', models.FileField(upload_to='layer/')),
                ('layer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_data', to='core.Layer')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_budget', to='core.Program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_data_program', to='core.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_population', models.IntegerField()),
                ('area', models.FloatField()),
                ('population_density', models.IntegerField()),
                ('poverty_rate', models.FloatField()),
                ('population_under_poverty_line', models.IntegerField()),
                ('per_capita_income', models.IntegerField()),
                ('hh_by_lowest_wealth_quantiles', models.FloatField()),
                ('human_development_index', models.FloatField()),
                ('minute_access_to', models.FloatField()),
                ('vulnerability_index', models.FloatField()),
                ('gdp', models.IntegerField()),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_data', to='core.Province')),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_info', to='core.Province')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_data_program', to='core.Program')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_data_sector', to='core.Sector')),
            ],
        ),
        migrations.AddField(
            model_name='programdata',
            name='province',
            field=models.ManyToManyField(related_name='program_data_province', to='core.Province'),
        ),
        migrations.AddField(
            model_name='layer',
            name='sector',
            field=models.ManyToManyField(related_name='layer', to='core.Sector'),
        ),
        migrations.AddField(
            model_name='indicatordata',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_data_province', to='core.Province'),
        ),
        migrations.AddField(
            model_name='districtspending',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_spending_program', to='core.Program'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts', to='core.Province'),
        ),
    ]
