# Generated by Django 2.0.4 on 2018-04-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='created_date',
        ),
    ]
