# Generated by Django 2.0.4 on 2018-05-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerdata',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
