# Generated by Django 2.0.4 on 2018-05-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180513_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerdata',
            name='file',
            field=models.FileField(upload_to='layer/'),
        ),
    ]
