# Generated by Django 2.0.4 on 2018-05-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180515_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerdata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='layer/'),
        ),
    ]
