# Generated by Django 2.0.4 on 2018-04-13 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180413_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_population', models.IntegerField()),
                ('area', models.FloatField()),
                ('population_desnity', models.IntegerField()),
                ('poverty_rate', models.FloatField()),
                ('population_under_poverty_line', models.IntegerField()),
                ('per_capita_income', models.IntegerField()),
                ('hh_by_lowest_wealth_quantiles', models.FloatField()),
                ('human_development_index', models.FloatField()),
                ('minute_access_to', models.FloatField()),
                ('vulnerability_index', models.FloatField()),
                ('gdp', models.IntegerField()),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_data', to='core.Province')),
            ],
        ),
    ]
