# Generated by Django 2.0.4 on 2018-06-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hlcit_code', models.IntegerField(unique=True)),
                ('type', models.CharField(max_length=300)),
                ('local_name', models.CharField(max_length=300)),
                ('programs', models.ManyToManyField(blank=True, null=True, to='core.Program')),
            ],
        ),
    ]
