# Generated by Django 2.0.4 on 2018-06-14 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180614_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='glossary',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='source',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Program'),
        ),
    ]
