# Generated by Django 2.0.4 on 2018-06-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180614_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='programs',
            field=models.ManyToManyField(blank=True, to='core.ProgramData'),
        ),
    ]
