# Generated by Django 2.0.4 on 2018-06-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180614_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='glossary',
            field=models.TextField(null=True),
        ),
    ]
