# Generated by Django 2.0.4 on 2018-06-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180615_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='provinceinfo',
            name='total_budget',
            field=models.FloatField(null=True),
        ),
    ]
