# Generated by Django 2.0.4 on 2018-06-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_provinceinfo_total_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provinceinfo',
            name='total_budget',
        ),
    ]
