# Generated by Django 2.0.4 on 2018-06-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_provinceinfo_total_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='provinceinfo',
            name='total_budget',
            field=models.FloatField(null=True),
        ),
    ]
