# Generated by Django 2.0.4 on 2018-06-22 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_glossarydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdf')),
                ('province', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Province')),
            ],
        ),
    ]
