# Generated by Django 2.0.4 on 2018-06-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180622_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='program',
            field=models.ManyToManyField(related_name='partner_program', to='core.ProgramData'),
        ),
    ]
