# Generated by Django 2.0.4 on 2018-06-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180622_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
