# Generated by Django 2.0.4 on 2018-06-28 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_pdf_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_province', to='core.Province'),
        ),
    ]
