# Generated by Django 2.0.4 on 2018-07-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_poverty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrydata',
            options={'verbose_name': 'Country Data'},
        ),
        migrations.AlterModelOptions(
            name='districtspending',
            options={'verbose_name': 'District Spending'},
        ),
        migrations.AlterModelOptions(
            name='glossarydata',
            options={'verbose_name': 'Glossary Data'},
        ),
        migrations.AlterModelOptions(
            name='indicatordata',
            options={'verbose_name': 'Indicator Data'},
        ),
        migrations.AlterModelOptions(
            name='layerdata',
            options={'verbose_name': 'Layer Data'},
        ),
        migrations.AlterModelOptions(
            name='pdf',
            options={'verbose_name': 'Pdf'},
        ),
        migrations.AlterModelOptions(
            name='poverty',
            options={'verbose_name': 'Poverty'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Program'},
        ),
        migrations.AlterModelOptions(
            name='programbudget',
            options={'verbose_name': 'Program Budget'},
        ),
        migrations.AlterModelOptions(
            name='programdata',
            options={'verbose_name': 'Program Data'},
        ),
        migrations.AlterModelOptions(
            name='provincedata',
            options={'verbose_name': 'Province Data'},
        ),
        migrations.AlterModelOptions(
            name='provinceinfo',
            options={'verbose_name': 'Province Info'},
        ),
        migrations.AlterModelOptions(
            name='sectordata',
            options={'verbose_name': 'Sector Data'},
        ),
    ]
