# Generated by Django 2.0.4 on 2018-07-31 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20180731_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectordata',
            options={'verbose_name': 'SectorData'},
        ),
    ]
