# Generated by Django 2.0.4 on 2018-07-31 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20180731_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectordata',
            options={'verbose_name_plural': 'Sector Data'},
        ),
    ]
