# Generated by Django 2.0.4 on 2018-07-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20180731_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrydata',
            options={'verbose_name_plural': 'Country Data'},
        ),
        migrations.AlterModelOptions(
            name='districtspending',
            options={},
        ),
        migrations.AlterModelOptions(
            name='glossarydata',
            options={'verbose_name_plural': 'Glossary Data'},
        ),
        migrations.AlterModelOptions(
            name='indicatordata',
            options={'verbose_name_plural': 'Indicator Data'},
        ),
        migrations.AlterModelOptions(
            name='layerdata',
            options={'verbose_name_plural': 'Layer Data'},
        ),
        migrations.AlterModelOptions(
            name='poverty',
            options={'verbose_name_plural': 'Poverty'},
        ),
        migrations.AlterModelOptions(
            name='programbudget',
            options={},
        ),
        migrations.AlterModelOptions(
            name='programdata',
            options={'verbose_name_plural': 'Program Data'},
        ),
        migrations.AlterModelOptions(
            name='provincedata',
            options={'verbose_name_plural': 'Province Data'},
        ),
        migrations.AlterModelOptions(
            name='provinceinfo',
            options={'verbose_name_plural': 'Province Information'},
        ),
    ]
