# Generated by Django 2.0.4 on 2018-07-31 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20180731_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name_plural': 'Municipal names and program details'},
        ),
        migrations.AlterModelOptions(
            name='districtspending',
            options={'verbose_name_plural': 'District Spending'},
        ),
        migrations.AlterModelOptions(
            name='pdf',
            options={'verbose_name_plural': 'Pdf'},
        ),
        migrations.AlterModelOptions(
            name='programbudget',
            options={'verbose_name_plural': 'Program Budget'},
        ),
    ]
