# Generated by Django 2.0.4 on 2018-07-31 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20180731_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrydata',
            options={'verbose_name_plural': 'Key indicators, national'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name_plural': 'District names'},
        ),
        migrations.AlterModelOptions(
            name='districtspending',
            options={'verbose_name_plural': 'Program annual spend, by district'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name_plural': 'Indicator names'},
        ),
        migrations.AlterModelOptions(
            name='indicatordata',
            options={'verbose_name_plural': 'indicator data, by province'},
        ),
        migrations.AlterModelOptions(
            name='layer',
            options={'verbose_name_plural': 'Geospatial data -- sectoral allocation'},
        ),
        migrations.AlterModelOptions(
            name='layerdata',
            options={'verbose_name_plural': 'Geospatial data -- metadata'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name_plural': 'Partner names and metadata'},
        ),
        migrations.AlterModelOptions(
            name='pdf',
            options={'verbose_name_plural': 'Infographics (metadata)'},
        ),
        migrations.AlterModelOptions(
            name='poverty',
            options={'verbose_name_plural': 'Poverty indicators, by municipality'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name_plural': 'Program names'},
        ),
        migrations.AlterModelOptions(
            name='programbudget',
            options={'verbose_name_plural': 'Program budgets (overlal)'},
        ),
        migrations.AlterModelOptions(
            name='programdata',
            options={'verbose_name_plural': 'Program allocations to provinces'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name_plural': 'Province names'},
        ),
        migrations.AlterModelOptions(
            name='provincedata',
            options={'verbose_name_plural': 'Key indicators, by province'},
        ),
        migrations.AlterModelOptions(
            name='provinceinfo',
            options={'verbose_name_plural': 'Total budget, by province'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name_plural': 'Sector names and codes'},
        ),
        migrations.AlterModelOptions(
            name='sectordata',
            options={'verbose_name_plural': 'Sectoral allocations of programs'},
        ),
    ]
