# Generated by Django 2.0.4 on 2018-07-31 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20180731_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
