# Generated by Django 2.0.4 on 2018-08-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About'},
        ),
    ]
