# Generated by Django 2.0.4 on 2018-08-03 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20180802_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name_plural': 'Municipal Names And Program Details'},
        ),
        migrations.AlterModelOptions(
            name='countrydata',
            options={'verbose_name_plural': 'Key Indicators, National'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name_plural': 'District Names'},
        ),
        migrations.AlterModelOptions(
            name='districtspending',
            options={'verbose_name_plural': 'Program Annual Spend, By District'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name_plural': 'Indicator Names'},
        ),
        migrations.AlterModelOptions(
            name='indicatordata',
            options={'verbose_name_plural': 'Indicator Data, By Province'},
        ),
        migrations.AlterModelOptions(
            name='layer',
            options={'verbose_name_plural': 'Geospatial Data -- Sectoral Allocation'},
        ),
        migrations.AlterModelOptions(
            name='layerdata',
            options={'verbose_name_plural': 'Geospatial Data -- Metadata'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name_plural': 'Partner Names And Metadata'},
        ),
        migrations.AlterModelOptions(
            name='poverty',
            options={'verbose_name_plural': 'Poverty Indicators, by Municipality'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name_plural': 'Program Names'},
        ),
        migrations.AlterModelOptions(
            name='programbudget',
            options={'verbose_name_plural': 'Program Budgets (Overall)'},
        ),
        migrations.AlterModelOptions(
            name='programdata',
            options={'verbose_name_plural': 'Program Allocations To Provinces'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name_plural': 'Province Names'},
        ),
        migrations.AlterModelOptions(
            name='provincedata',
            options={'verbose_name_plural': 'Key Indicators, By Province'},
        ),
        migrations.AlterModelOptions(
            name='provinceinfo',
            options={'verbose_name_plural': 'Total Budget, By Province'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name_plural': 'Sector Names And Codes'},
        ),
        migrations.AlterModelOptions(
            name='sectordata',
            options={'verbose_name_plural': 'Sectoral Allocations Of Programs'},
        ),
    ]
