# Generated by Django 2.0.4 on 2018-08-03 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20180803_0353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poverty',
            options={'verbose_name_plural': 'Poverty Indicators, By Municipality'},
        ),
    ]
