# Generated by Django 2.0.4 on 2018-08-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20180803_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerdata',
            name='layer_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='layerdata',
            name='layer_server_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
