# Generated by Django 2.0.4 on 2018-08-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_programspendallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programspendallocation',
            name='district',
            field=models.CharField(max_length=300),
        ),
    ]
