# Generated by Django 2.0.4 on 2018-08-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20180828_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programspendallocation',
            old_name='partneship',
            new_name='partnership',
        ),
    ]
