# Generated by Django 2.0.4 on 2018-08-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20180828_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programspendallocation',
            name='hlcit_code',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
