# Generated by Django 2.0.4 on 2018-08-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20180828_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='programs',
            field=models.ManyToManyField(blank=True, to='core.ProgramSpendAllocation'),
        ),
    ]
