# Generated by Django 2.0.4 on 2018-08-30 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20180830_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='programs',
        ),
        migrations.AlterField(
            model_name='programspendallocation',
            name='hlcit_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipality_program_spend', to='core.Area'),
        ),
    ]
