# Generated by Django 2.0.4 on 2018-08-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20180830_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='program',
            field=models.ManyToManyField(related_name='partner_program', to='core.Program'),
        ),
    ]
