# Generated by Django 2.0.4 on 2018-08-30 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20180830_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programspendallocation',
            name='hlcit_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.Area'),
        ),
    ]
